### ISSUE TITLE
Crashes on search

### ISSUE THREAD

**Issue by mterencelao** [DaKnig/DewDuct#10]
Attempted to use the search function, but the app crashes shortly after returning results. Stack trace, as returned by `RUST_BACKTRACE=full`:
```
thread 'main' panicked at src/channel_row.rs:126:10:
called `Result::unwrap()` on an `Err` value: ()
stack backtrace:
   0:       0x558335d228 - <unknown>
   1:       0x55832d6564 - <unknown>
   2:       0x558333943c - <unknown>
   3:       0x558335e418 - <unknown>
   4:       0x558335dd70 - <unknown>
   5:       0x558335ebac - <unknown>
   6:       0x558335e714 - <unknown>
   7:       0x558335e67c - <unknown>
   8:       0x558335e674 - <unknown>
   9:       0x558328b764 - <unknown>
  10:       0x558328b9e4 - <unknown>
  11:       0x55832ce4c8 - <unknown>
  12:       0x55832a0308 - <unknown>
  13:       0x55832ea7f0 - <unknown>
  14:       0x7f8cd26300 - <unknown>
  15:       0x7f8cd29a10 - <unknown>
  16:       0x7f8cd2a154 - g_main_context_iteration
  17:       0x7f8cf22620 - g_application_run
  18:       0x55832d19d8 - <unknown>
  19:       0x55832cf170 - <unknown>
  20:       0x5583298e1c - <unknown>
Aborted
```

Nice work in progress, by the way. A light player seems much preferable than invoking `mpv`, not that I have anything bad to say about the app. And when will preferences be implemented? I'm thinking of changing the preset Invidious instance.

**Comment by DaKnig** [comment]
this issue was fixed in the latest commit in master, try building again.
please open separate issues separately. but, regarding mpv, you would need to make sure that whichever player you want, can play youtube streams (most likely through yt-dlp). and configure the flags or whatever. I'd get around to that later. development is slowing down due to overworked fingers and fear of RSI.

**Comment by mterencelao** [comment]
My apologies. I should have mentioned I used the release build in the pmOS/Alpine edge repository. Looking forward to more updates for this client, and I wish you well.

**Comment by DaKnig** [comment]
wow somebody actually used that! sure, will make a release this weekend then

**Comment by DaKnig** [comment]
please try the new version merged *just now* into alpine :)
