### ISSUE TITLE
Add screenshots

### ISSUE THREAD

**Issue by DaKnig** [DaKnig/DewDuct#4]

**Comment by DaKnig** [comment]
Partially solved, they need to be cropped to fit better on screen.

**Comment by 1peter10** [comment]
If I may utter a recommendation:
Please put the screenshots somewhere into the repo, as the current image URLs are very, very long: 

https://private-user-images.githubusercontent.com/37626476/325948567-4ea8957e-99d4-4ebc-aaf6-8893784d6df8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MTg3NzgsIm5iZiI6MTcxNDkxODQ3OCwicGF0aCI6Ii8zNzYyNjQ3Ni8zMjU5NDg1NjctNGVhODk1N2UtOTlkNC00ZWJjLWFhZjYtODg5Mzc4NGQ2ZGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDE0MTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmMWM5Y2M4ZDI2MzMwNTY5MDk1Njc0OTkyMDFmYmI1NmI1MGY0Nzg4ZmJhMjNhYmNjNTVjYTFhYjIxZTRlNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fnsXtUam1B_xPEgxzKKdzIOI-5LMdz0vTbQNrikT3nI

data/screenshots/ would be a good location.

**Comment by DaKnig** [comment]
I want to avoid that as that increases the size of the repo and is impossible to repair
the .git folder will forever contain a compressed version of the screenshot, it's the same as putting a binary in the repo.
if you have a better solution, somewhere safe that wont get deleted then you are welcome to upload there, I will link.

also it is a common mis-recommendation in general.

**Comment by DaKnig** [comment]
Done.
